# 숙제 1번

In [1]:
import numpy as np

In [12]:
# zero padding을 크기 1만큼 적용 
a=np.array([[0, 0, 0, 0, 0, 0, 0, 0],
            [0, 2, 0, 2, 1, 3, 2, 0],
            [0, 0, 2, 0, 2, 2, 2, 0],
            [0, 1, 0, 1, 3, 1, 1, 0],
            [0, 0, 0, 1, 1, 1, 0, 0],
            [0, 0, 1, 3, 4, 1, 0, 0],
            [0, 0, 1, 0, 0, 5, 2, 0],
            [0, 0, 0, 0, 0, 0, 0, 0]])
a

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 2, 1, 3, 2, 0],
       [0, 0, 2, 0, 2, 2, 2, 0],
       [0, 1, 0, 1, 3, 1, 1, 0],
       [0, 0, 0, 1, 1, 1, 0, 0],
       [0, 0, 1, 3, 4, 1, 0, 0],
       [0, 0, 1, 0, 0, 5, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [36]:
A = np.array([[1, 0, 0],
               [0, 1, 0],
               [0, 0, 1]])
A

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [102]:
r = [0,1,2,3,4,5]
k = np.empty((6 ,6), int)
k

array([[4128860, 6029375, 3801155, 5570652, 6619251, 7536754],
       [7536732, 7143521, 7667827, 6750318, 3014748, 7340137],
       [7602297, 7274600, 6029422, 7471216, 6684783, 7077993],
       [6226021, 6619236, 6357094, 7078005, 6029428, 6881384],
       [7602291, 7471215, 3014777, 7405683, 6881388, 6619252],
       [6946861, 7667823, 7209074, 7077985, 3014656, 7929968]])

In [103]:
for j in r:
    for i in r:
        kk= a[j:j+3,i:i+3] * A
        k[j,i]= sum(sum(kk))

In [104]:
# stride (1,1)로 filter A 적용 
k

array([[ 4,  0,  4,  3,  5,  2],
       [ 0,  5,  3,  5,  4,  5],
       [ 1,  1,  4,  4,  3,  3],
       [ 1,  4,  5,  3,  4,  1],
       [ 1,  1,  3, 10,  4,  1],
       [ 0,  1,  1,  3,  9,  3]])

In [98]:
k1 = np.empty((3,3), int)
rr = [0, 1, 2]

In [100]:
    for j in rr:
        for i in rr:
            k1[j, i] = np.max(k[j*2:j*2+2, i*2:i*2+2])
            

In [101]:
# stride(2,2)로 maxpooling 적용 
k1

array([[ 5,  5,  5],
       [ 4,  5,  4],
       [ 1, 10,  9]])

# 숙제 2번

In [115]:
import torch 
import torch.nn as nn
import torchvision.datasets as dsets
import torchvision.transforms as transforms

import torch.nn.init

In [116]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

torch.manual_seed(777)
if device == 'cuda' :
    torch.cuda.manual_seed_all(777)

In [126]:
# Parameters
learning_rate=0.001
training_epochs=10
batch_size=100

In [131]:
# MNIST dataset

mnist_train = dsets.MNIST(root="MNIST_data/",
                         train=True,
                         transform=transforms.ToTensor(),
                         download=True)

mnist_test = dsets.MNIST(root="MNIST_data/",
                        train=False,
                        transform=transforms.ToTensor(),
                        download=True)

Extracting MNIST_data/MNIST\raw\train-images-idx3-ubyte.gz to MNIST_data/MNIST\raw


Extracting MNIST_data/MNIST\raw\train-labels-idx1-ubyte.gz to MNIST_data/MNIST\raw



Extracting MNIST_data/MNIST\raw\t10k-images-idx3-ubyte.gz to MNIST_data/MNIST\raw


Extracting MNIST_data/MNIST\raw\t10k-labels-idx1-ubyte.gz to MNIST_data/MNIST\raw
Processing...


..\torch\csrc\utils\tensor_numpy.cpp:141: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program.


Done!


In [132]:
# Data Loader
data_loader = torch.utils.data.DataLoader(dataset=mnist_train,
                                         batch_size=batch_size,
                                         shuffle=True,
                                         drop_last=True)

우선, Layer1의 Kernel_size는 4로, Layer3의 stride는 2로 조정하고<br>
그 결과 달라지는 Layer3 의 output size계산 <br>
$Output\; size = \frac{input \;size-filter \;size+(2*padding)}{Stride}+1$

In [156]:
# Layer1
conv1=nn.Conv2d(1,32,kernel_size=4, stride=1, padding=1)
pool=nn.MaxPool2d(2)

# Layer2
conv2=nn.Conv2d(32,64,kernel_size=3, stride=2, padding=1)

# Layer3
conv3=nn.Conv2d(64,128,kernel_size=3, stride=1, padding=1)

In [158]:
out=conv1(X)
out.shape

torch.Size([100, 32, 27, 27])

In [159]:
out=pool(out)
out.shape # Layer1의 output

torch.Size([100, 32, 13, 13])

In [160]:
out=conv2(out)
out.shape

torch.Size([100, 64, 7, 7])

In [161]:
out=pool(out)
out.shape# Layer2의 output

torch.Size([100, 64, 3, 3])

In [162]:
out=conv3(out)
out.shape

torch.Size([100, 128, 3, 3])

In [163]:
out=pool(out)
out.shape  # Layer3의 output

torch.Size([100, 128, 1, 1])

In [164]:


class CNN(nn.Module):
    
    def __init__(self):
        super(CNN, self).__init__()
        self.layer1 = nn.Sequential(
            nn.Conv2d(1,32,kernel_size=4, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )
        
        self.layer2 = nn.Sequential(
            nn.Conv2d(32,64,kernel_size=3, stride=2, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )
        
        self.layer3 = nn.Sequential(
            nn.Conv2d(64,128,kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )        
        
        # Fully connected layer (마지막 layer)
        self.fc1 = nn.Linear(1*1*128, 625)
        self.relu = nn.ReLU()
        
        self.fc2 = nn.Linear(625, 10, bias=True)
        
        torch.nn.init.xavier_uniform_(self.fc1.weight) 
        torch.nn.init.xavier_uniform_(self.fc2.weight) 
        
    
    def forward(self, x):
        out = self.layer1(x) 
        out = self.layer2(out)
        out = self.layer3(out)
        
        out = out.view(out.size(0), -1) # fc돌리기 전에 view로 펼치기 
        out = self.fc1(out)
        out = self.relu(out)
        out = self.fc2(out)
        return out

In [165]:
model = CNN().to(device)  # device는 cuda, cpu 중에서 사용가능한거 쓰겟다 옵션 

In [166]:
criterion = nn.CrossEntropyLoss().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [167]:
# Training 
total_batch = len(data_loader)
print(total_batch)

for epoch in range(training_epochs):
    avg_cost = 0
    
    for X,Y in data_loader : 
        X=X.to(device) # 이미지 (input)
        Y=Y.to(device) # 라벨
        
        optimizer.zero_grad() ## 중요중요 ##
        hypothesis = model(X) # model에 X input 대입한 결과 (가설)
        
        cost = criterion(hypothesis, Y) # 그 가설과 실제 라벨 사이의 차이 계산(Loss)
        cost.backward()
        optimizer.step() # 모델 학습 
        
        avg_cost += cost / total_batch # cost 쌓기 
        
    print('[Epoch:{}] cost = {}'.format(epoch+1, avg_cost))
    
print('Learning Finished!')

600
[Epoch:1] cost = 0.24443699419498444
[Epoch:2] cost = 0.06653865426778793
[Epoch:3] cost = 0.045752834528684616
[Epoch:4] cost = 0.03580816462635994
[Epoch:5] cost = 0.029082652181386948
[Epoch:6] cost = 0.02241525985300541
[Epoch:7] cost = 0.017565149813890457
[Epoch:8] cost = 0.0186750628054142
[Epoch:9] cost = 0.01441432535648346
[Epoch:10] cost = 0.011911477893590927
Learning Finished!


In [173]:
with torch.no_grad(): # test는 학습을 안할꺼니까 no gradient
    X_test = mnist_test.test_data.view(len(mnist_test), 1, 28, 28).float().to(device)
    Y_test = mnist_test.test_labels.to(device)
    
    prediction = model(X_test)
    correct_prediction = torch.argmax(prediction,1) == Y_test
    accuracy = correct_prediction.float().mean()
    print('Accurary:', accuracy.item())

C:\ProgramData\Anaconda3\lib\site-packages\torchvision\datasets\mnist.py:60: UserWarning: test_data has been renamed data
  warnings.warn("test_data has been renamed data")
C:\ProgramData\Anaconda3\lib\site-packages\torchvision\datasets\mnist.py:50: UserWarning: test_labels has been renamed targets
  warnings.warn("test_labels has been renamed targets")


Accurary: 0.9782000184059143


# 기존 CNN모델 

In [174]:
# Model2

class CNN(nn.Module):
    
    def __init__(self):
        super(CNN, self).__init__()
        self.layer1 = nn.Sequential(
            nn.Conv2d(1,32,kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )
        
        self.layer2 = nn.Sequential(
            nn.Conv2d(32,64,kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )
        
        self.layer3 = nn.Sequential(
            nn.Conv2d(64,128,kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )        
        
        # Fully connected layer (마지막 layer)
        self.fc1 = nn.Linear(3*3*128, 625)
        self.relu = nn.ReLU()
        
        self.fc2 = nn.Linear(625, 10, bias=True)
        
        torch.nn.init.xavier_uniform_(self.fc1.weight) 
        torch.nn.init.xavier_uniform_(self.fc2.weight) 
        
    
    def forward(self, x):
        out = self.layer1(x) 
        out = self.layer2(out)
        out = self.layer3(out)
        
        out = out.view(out.size(0), -1) # fc돌리기 전에 view로 펼치기 
        out = self.fc1(out)
        out = self.relu(out)
        out = self.fc2(out)
        return out

In [175]:
model = CNN().to(device)

In [176]:
criterion = nn.CrossEntropyLoss().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [177]:
# Training 
total_batch = len(data_loader)
print(total_batch)

for epoch in range(training_epochs):
    avg_cost = 0
    
    for X,Y in data_loader : 
        X=X.to(device) # 이미지 (input)
        Y=Y.to(device) # 라벨
        
        optimizer.zero_grad() ## 중요중요 ##
        hypothesis = model(X) # model에 X input 대입한 결과 (가설)
        
        cost = criterion(hypothesis, Y) # 그 가설과 실제 라벨 사이의 차이 계산(Loss)
        cost.backward()
        optimizer.step() # 모델 학습 
        
        avg_cost += cost / total_batch # cost 쌓기 
        
    print('[Epoch:{}] cost = {}'.format(epoch+1, avg_cost))
    
print('Learning Finished!')

600
[Epoch:1] cost = 0.15828467905521393
[Epoch:2] cost = 0.04280175641179085
[Epoch:3] cost = 0.02909858524799347
[Epoch:4] cost = 0.02253478765487671
[Epoch:5] cost = 0.016964666545391083
[Epoch:6] cost = 0.015744905918836594
[Epoch:7] cost = 0.012974976561963558
[Epoch:8] cost = 0.010625616647303104
[Epoch:9] cost = 0.008913536556065083
[Epoch:10] cost = 0.007716613356024027
Learning Finished!


In [178]:
with torch.no_grad(): # test는 학습을 안할꺼니까 no gradient
    X_test = mnist_test.test_data.view(len(mnist_test), 1, 28, 28).float().to(device)
    Y_test = mnist_test.test_labels.to(device)
    
    prediction = model(X_test)
    correct_prediction = torch.argmax(prediction,1) == Y_test
    accuracy = correct_prediction.float().mean()
    print('Accurary:', accuracy.item())

Accurary: 0.9821000099182129
